Player.create!(name: "Gabby Debson", email: "debbyd@ddd.gabby.com")
Player.create!(name: "Tom Cruise", email: "cruisin@brusin.scientology.net")
Player.create!(name: "Max Power", email: "maximumpower@wustl.dot.edu")
Player.create!(name: "Marion Cobretti", email: "toothpick@sunglasses.com")

Prize.create!(name: "80s Toy", amount: 20)
Prize.create!(name: "T-Shirt", amount: 10)
Prize.create!(name: "YOUR PICK", amount: 20)
Prize.create!(name: "80s Cassette", amount: 20)
Prize.create!(name: "80s VHS Tape", amount: 10)
Prize.create!(name: "80s Pin", amount: 20)
Prize.create!(name: "Rubik's Cube", amount: 30)
Prize.create!(name: "80s Poster", amount: 12)