Player.create!(name: "Gabby Debson", email: "debbyd@ddd.gabby.com")
Player.create!(name: "Tom Cruise", email: "cruisin@brusin.scientology.net")
Player.create!(name: "Max Power", email: "maximumpower@wustl.dot.edu")
Player.create!(name: "Marion Cobretti", email: "toothpick@sunglasses.com")

Prize.create!(name: "T-Shirt", amount: 10)
Prize.create!(name: "Gremlin", amount: 1)
Prize.create!(name: "Pretty in Pink", amount: 1)
Prize.create!(name: "Scarface", amount: 1)
Prize.create!(name: "Thundercat", amount: 1)
Prize.create!(name: "Smurf", amount: 3)
Prize.create!(name: "CA Raisins", amount: 3)
Prize.create!(name: "Hulk Hogan", amount: 1)
Prize.create!(name: "Macho Man", amount: 1)
Prize.create!(name: "Rowdy Roddy Piper", amount: 1)
Prize.create!(name: "Dealer's Choice!", amount: 10)